# Generated by Django 3.1.3 on 2020-11-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=True, verbose_name='Мероприятие проходит весь день'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(null=True, verbose_name='Время окончания мероприятия'),
        ),
    ]
