# Generated by Django 3.1.3 on 2020-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201112_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='note',
            field=models.TextField(default='', verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='Мероприятие проходит весь день'),
        ),
    ]
